In [4]:
import json
from tqdm import tqdm
import re
import torch

# 定义 color_mapping
color_mapping = {
    'red': [0.1, 0.15],
    'green': [0.15, 0.3],
    'blue': [0.3, 0.45],
    'yellow': [0.45, 0.6],
    'orange': [0.6, 0.75],
    'purple': [0.75, 0.9]
}

# 提取所有颜色
colors = color_mapping.keys()

# 检查颜色是否存在于字符串中
def find_colors_in_string(input_string):
    found_colors = [color for color in colors if color in input_string]
    return found_colors


def map_to_color(pixel):
    if pixel<0.1:
        return 'black'
    elif 0.1<=pixel<0.15:
        return 'red'
    elif 0.15<=pixel<0.3:
        return 'green'
    elif 0.3<=pixel<0.45:
        return 'blue'
    elif 0.45<=pixel<0.6:
        return 'yellow'
    elif 0.6<=pixel<0.75:
        return 'orange'
    elif 0.75<=pixel<=0.9:
        return 'purple'
    else:
        return 'other'

def compare_img(gen_img,gt_img):
    correct_pixel=0
    incorrect_pixel=0
    for i in range(len(gen_img)):
        for j in range(len(gen_img[i])):
            if map_to_color(gen_img[i][j])!=map_to_color(gt_img[i][j]):
                incorrect_pixel+=1
            else:
                correct_pixel+=1
    return correct_pixel,incorrect_pixel

acc=[]
for i in range (0,5):
    #data_path=f'/datadrive_a/jihai/LLaVA/answer/answer-llava-v1.5-7b-mix-u-odd-{i}.jsonl'
    data_path=f'/datadrive_a/jihai/LLaVA/answer/answer-llava-v1.5-7b-affine2-lora-{i}.jsonl'
    correct_piexl=0
    incorrect_pixel=0
    correct_time=0
    incorrect_time=0
    correct_color=0
    incorrect_color=0
    count=0
    bound=5
    with open (data_path, "r") as f:
        for line in tqdm(f):
            # count+=1
            # if count<bound:
            #     continue
            # if count>bound:
            #     break
            json_obj = json.loads(line.strip())
            #print(json_obj)
            # generation:
            if '<image>' in json_obj['groun_truth']:
                gt_img=json_obj['groun_truth_img_tensor']
                gen_img=json_obj['output_img_tensor']
                if gen_img !=None:
                    correct,incorrect=compare_img(gen_img,gt_img)
                    correct_piexl+=correct
                    incorrect_pixel+=incorrect
                else:
                    incorrect_pixel+=6*7
            else:
                gt_time=re.findall(r'\d+',json_obj['groun_truth'])
                gen_time=re.findall(r'\d+',json_obj['answer'])
                if len(gen_time)!=0:
                    for i in range(len(gt_time)):
                        if i<len(gen_time) and gt_time[i]==gen_time[i]:
                            correct_time+=1
                        else:
                            incorrect_time+=1
                else:
                    incorrect_time+=3
                gt_color=find_colors_in_string(json_obj['groun_truth'])
                gen_color=find_colors_in_string(json_obj['answer'])
                if len(gen_color)!=0 and gt_color[0]==gen_color[0]:
                    correct_color+=1
                else:
                    incorrect_color+=1
    acc.append([correct_piexl/(correct_piexl+incorrect_pixel),correct_time/(correct_time+incorrect_time),correct_color/(correct_color+incorrect_color)])
    print(f"generation_accuracy:{correct_piexl/(correct_piexl+incorrect_pixel)}")
    print(f"time_accuracy:{correct_time/(correct_time+incorrect_time)}")
    print(f"color_accuracy:{correct_color/(correct_color+incorrect_color)}")
acc=torch.Tensor(acc)
acc=acc.permute(1,0)
print(acc[0])
print(acc[1])
print(acc[2])


200it [00:00, 15404.09it/s]


generation_accuracy:0.29863945578231293
time_accuracy:0.03508771929824561
color_accuracy:0.5894736842105263


200it [00:00, 7535.85it/s]


generation_accuracy:0.7625850340136054
time_accuracy:0.031578947368421054
color_accuracy:0.9052631578947369


200it [00:00, 17740.15it/s]


generation_accuracy:0.9467120181405896
time_accuracy:0.1368421052631579
color_accuracy:0.9578947368421052


200it [00:00, 17206.70it/s]


generation_accuracy:0.9571428571428572
time_accuracy:0.5333333333333333
color_accuracy:0.8736842105263158


200it [00:00, 26913.30it/s]

generation_accuracy:0.9691609977324263
time_accuracy:0.7789473684210526
color_accuracy:0.9368421052631579
tensor([0.2986, 0.7626, 0.9467, 0.9571, 0.9692])
tensor([0.0351, 0.0316, 0.1368, 0.5333, 0.7789])
tensor([0.5895, 0.9053, 0.9579, 0.8737, 0.9368])


In [12]:
print(':'.join(gt_time))

18:14:20


In [8]:
from sklearn import kernel_approximation
import torch
import torch.nn.functional as F
padded_input=torch.Tensor([[0., 0., 0., 1., 0., 0.],
        [1., 0., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 1., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [1., 0., 1., 1., 1., 0.]]).unsqueeze(0).unsqueeze(0)
padded_input=torch.Tensor([[0., 1., 1., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 0., 0., 1.],
        [0., 0., 1., 0., 0., 0.],
        [0., 1., 1., 1., 0., 1.],
        [0., 0., 0., 0., 0., 0.]]).unsqueeze(0).unsqueeze(0)
kernel=torch.Tensor([[1, 0, 3],
    [0, 0, 2],
    [4, 1, 0]]).unsqueeze(0).unsqueeze(0) 
output = F.conv2d(padded_input, kernel, stride=1)
print(output)

tensor([[[[4., 9., 5., 4.],
          [2., 1., 4., 2.],
          [6., 6., 6., 7.],
          [5., 2., 1., 2.]]]])
